quadrotor_env:
   camera: yes
   sim_dt: 0.02 
   max_t: 5.0
   init_pos: [-10.0, 0.0, 2.5]  # initial position of the quadrotor (x, y, z)
  # Drone starts at [-10, 0, 2.5] facing Yaw 0 (East)
   gates:
    # ---  CIRCLE ---
    - pos: [-10.0, 3.0, 2.5]
      yaw: 0.0
    
    - pos: [-5.0, 8.0, 2.5]
      yaw:  1.57

    - pos: [0.0, 3.0, 2.5]
      yaw: 0.0

    - pos: [-5.0, -2.0, 2.5]
      yaw:  1.57

    # --- CUSTOM OVAL  ---

    # # 1. First Gate (Straight ahead, 5m away)
    # - pos: [-10.0, 3.0, 2.5]
    #   yaw: 0.0

    # # 2. Second Gate (Straight ahead, 10m away - entering turn)
    # - pos: [-5.0, 8.0, 2.5]
    #   yaw: -0.4 # 20 

    # # 3. Far East Turn (Banking Left)
    # - pos: [3.0, 8.0, 2.5]
    #   yaw: 0.4 # -20 

    # # 4. Back Straight 
    # - pos: [7.0, 0.0, 2.5]
    #   yaw: 0.0 #   

    # # 5. Return Gate
    # - pos: [3.0, -6.0, 2.5]
    #   yaw: -0.4 #  

    # # 6. Final Turn (Banking Left to rejoin start)
    # - pos: [-5.0, -6.0, 2.5]
    #   yaw: 0.4 #  

quadrotor_dynamics:
  mass: 0.73
  arm_l: 0.17
  motor_omega_min: 150.0 # motor rpm min
  motor_omega_max: 3000.0 # motor rpm max
  motor_tau: 0.0001 # motor step response
  thrust_map: [1.3298253500372892e-06, 0.0038360810526746033, -1.7689986848125325]
  kappa: 0.016 # rotor drag coeff
  omega_max: [6.0, 6.0, 6.0]  # body rate constraint (x, y, z) 

rl:
  pos_coeff: -0.002        # reward coefficient for position 
  ori_coeff: -0.002        # reward coefficient for orientation
  lin_vel_coeff: -0.0002   # reward coefficient for linear velocity
  ang_vel_coeff: -0.0002   # reward coefficient for angular velocity
  act_coeff: -0.0002  # reward coefficient for control actions